name: WATI 24/7 Bot

on:
  schedule:
    - cron: "*/15 * * * *"   # Runs every 15 minutes
  workflow_dispatch:          # Allow manual start

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run WATI Automation
        run: python main.py
